### PR TITLE
Add Waveshare Pico-ResTouch-LCD-2.8 support

### PR DESCRIPTION
**Pull request by corranwebster**
This:
- adds a display driver for the Waveshare Pico-ResTouch-LCD-2.8
- refactors the ST7789 codebase somewhat now that we have a second example
- makes it easier to switch displays in the examples

Thanks to [@JoGeDuBo ](https://github.com/JoGeDuBo) for the information to make this work.

### CODE REVIEW

**Comment by JoGeDuBo** [comment]
Oh, that's quick.

I haven't tested the changes yet, it takes a little longer for me.
But for me as a tester it would be easier if it were solved like this:
instead of 
```
from tempe_displays.st7789.pimoroni import PimoroniDisplay as Display
```
in every example *example.py, write
```
from display import Display
```
and a separate script display.py with
```
from tempe_displays.st7789.pimoroni import PimoroniDisplay as Display
# from tempe_displays.st7789.waveshare import PicoResTouchDisplay as Display
```
Then I would have to change only one place to test all the examples.

**Comment by corranwebster** [comment]
Thanks for the feedback. There is a lot of commonality between the various example scripts and I'm torn between factoring that out into an "example support" module (which would have a single "init_display" that would mean one place to change things) vs. having each example self-contained so people can copy and modify more easily.

There are possibly other solutions - I'll open an issue and think about it.

**Comment by JoGeDuBo** [comment]
I have now done some tests with the current version. There is an (easily fixable) error in the initialization of the SPI which leads to the error message "ValueError: bad SCK pin". The first parameter of SPI() must be 1, not 0.

Unfortunately, I no longer get an image on the display (with any of the tested examples from line_plot_example to shapes_example).

I have tried both to integrate waveshare.py and to make the same changes in pymoroni.py that led to success so quickly last time.

The scripts run to the end without an error message and without an image appearing.

Now I'm pretty stumped.

**Comment by JoGeDuBo** [comment]
I looked around a bit and came across this in src/tempe/data_view.py in class Count(DataView):

```
    def __iter__(self):
        i = self.start
        while True:
            yield i
            i += 1
```

should not it say this?

```
            i += self.step
```

**Comment by corranwebster** [comment]
> I looked around a bit and came across this in src/tempe/data_view.py in class Count(DataView):
> 
> ```
>     def __iter__(self):
>         i = self.start
>         while True:
>             yield i
>             i += 1
> ```
> 
> should not it say this?
> 
> ```
>             i += self.step
> ```

Yes, that is indeed a problem.  Thanks for the catch, and I've opened #72 to track this.

**Comment by JoGeDuBo** [comment]
Found the error why nothing was shown on the waveshare display

in base.py, line 107

```
        if isinstance(reset_pin, int):
            # reset_pin = Pin(reset_pin, Pin.OUT) # wrong
            reset_pin = Pin(reset_pin, Pin.OUT, value=True) # right 
```

and lines 131, 132 could be left out:

```
            self.reset_pin(True)
            asyncio.sleep(0.500)
```

and, as in my penultimate post:
in waveshare.py, line 28,29

```
            spi = SPI(
                # 0, # wrong
                1, # right
```

**Comment by corranwebster** [comment]
Thanks - the devices I have don't have a reset pin wired, so I can't test.

**Comment by corranwebster** [comment]
The error with the reset pin could also be caused by missing `await` for the `asyncio.sleep` - the ST7789 Datasheet says you need to allow some time after reset before trying to do anything further.  I have fixed both in #78.

**Pull request merged**
